language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: PYLgcSbbXrphyxGcB8uoxwr4rpOs+ZeNQv5ngKwlIGZgny3qQymkRs7zXEU7S8JwjTtr66W+phiaaC1dONZtrgrTwsRbGY4EH0MwhTqsacumvpzTGVYNscGZyal8+3dNq2M9Y51jNYo3TuvTiyLqGrDkYx8PiNwofYMEJbznUIBMjC+AQO0OtrjcNn+idBYtO2B+3cGaWjJxtOhIexOm6hfxJ5b7KV9y3D1ejCWvyV9R30X1fmx36NpepGI/KCHKO2GujHlwFNJPXqDqFbVJd+U/PVOWT99JyvTOHaGL7NdAy+zl7kO1WHRyPb9n5KMfPibM55lHdGCfDPQQSTVMqNGKIdrk33EEb76hgvOHnQXaK0cPbn1zb2qEHoo8l1RpIXgKh6zprzcC31oYyU+2gMwVSZWQspnTx+FIXzB0AtoJorlXKz/V/uieffCxXN6mfeKe2SQqn4R86CNtFNrwRD7TJLH+dBQ55GYjrA5GAsui22n5RN+XxiEbf9P/8/ezKz1M06wOp5LhgoWUxKWezi0DE4zZbhNLFYuwtJk8YObQ7WHHEM/cuOkFqxnxYFlHsh1mlRjRkliLqJpJIUj8fjZXVS8XfInajfOaWp5dUk8bCId9dCWHh88c3kAFRXKvpXzWNerfCCv8g4aBUhK4LlL848NR/fm9esoGkmwAgO8=
  app: flasktaskr_proj
  on:
    repo: garyherd/flasktaskr
