language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: U2cga1uRtyAhzsjCvAfcvGR977l2wOts+c8rUKmux/aHjNGAuMYHk0Kg+Kf2HveOXI0z7qpe2NbwEqb0D3x192g7TyauZ8rCPqa5IrJAffIwduVdeHVCpQgn/RyIvXXs5BpwKqHN9cSmOtofvQGknXoO5mXEjYcwbyYeD7mxU2xdVNw/3SqlZMTuLP3gLwfeNEvsWzvsbKVMlL7eisG6HV4Xw5sgNwWq/Tq8DpwcaLP0I5xailknjlkKIBaaeUm/Ps4ng9VcuYtDHra1iyWR3vo0fOQHauyOUtmoUDI95s0t/4zoyo0QvI8Uwk5woLkjmkteywPhET9/lA2SXMqLxsvebRgjrriCrLG1lKG++zLFzRq4Fg0Cr8P8xJT1R8Op/AB7SEs34TpYmMMzX7MvkwkOq6t4dhydb2f2m3vwIvQbHxGMAYqEutM1roUuyV96ckvHKPaTgdQAHAKlKdELf5u8xqLEYneDXU8+St5mu/mExJwLHeWwZpEWOVDAZV3Ezg5Ci/onr0DjdKAFozuwKVjdJ1LdNWJ8RPo44tEiqre4HjA0h13bmytVJ0FYVb+dc06ZblpEyWBZGXkipkcxseDMtWSqSe/je0HXFu2D72z4stjtg47GliCp+6if+OZmi42fmYw2vOGCCPXvurK61i4dlv3YTZhlRECxM9MTjZc=
  app: flasktaskr
  on:
    repo: garyherd/flasktaskr
