language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: BAfhXez72mdUrXjed790h13nj/45gpebHw8RcTbu2SXBCKg8XzjET6O/Bk571higM29P8jYmxxgtCSdio/hLO3VsLM51nZv+ID9NLm1lLiT1jvRhBwQ0SH40kLgIrMiWVRXhI6efbA7XXt3IwQlr4QrQSzDBCgDTkC9+XtV49sXajP7kQGZvIzMhSwOj0BURSPUY61KFvk6dHRsg3J9MGL8IFnbrK30AD/BCb85CRsvpLpkCCz39K7uHqTTe8j1/oCI7Cr3YZ2cQc4bWXfYgMEu+nDtInrOwmWqpWVM0Hc0em9hwzystBFhhyGPWDTjZj52T/Y/NkJ5H/g3YOoa+pg6hzk/ukh/xCLhwwjkQYYEiR4Fzpbd3ooJedN3Vn1RYrAGdElpnMlZIAs5bvpgCKr9fVy8pW2kGiVlrNMwWGOaD5xgvrzdEOq1yPP+pe1qj5thh8Zmu+kFKPt05Lh/lK+GN8waCP1NgIDHA6hGv3/9YpUTSz0sY1ALXJbtLtKrjLKkYacKKKVyz47Q11lFX+an7DSKtOBlifX2TyKAmYFu0lcmM69iJuja4Aw1T0SkZa98JwqaSuRm4lmHOGCZ2p3WuxhXlQ6BUFa/I43VtjICbtJZmUwcJoAu5cxaCIl3y27qWyreOMHHuRtMCNFiQwZVRX9MNdBx6bUo99BOPwVk=
  app: flasktaskr
  on:
    repo: garyherd/flasktaskr
